Chore exam registration registrees
mumuki/mumuki-domain pull request #200
Opened 2021-03-30 18:40 UTC by luchotc

## :dart: Goal
We needed to actually save users that were registered in an ExamRegistration. The only bond was the Notification model and that was quite brittle.

## :back: Backwards compatibility
100%

2021-03-30 19:02 UTC, fedescarpa requested changes

2021-03-30 19:02 UTC, fedescarpa commented on app/models/exam_registration.rb
> +    registrees.each &method(:notify_user!)
I think that register should call start only for users that you are registering.
Now, if you start an exam registration and later add some users to the registration you will send the notification to all users, newer and olders.

2021-03-30 20:56 UTC, luchotc commented
@fedescarpa Fair enough. It was addressed so please review it again :smile:

2021-03-31 18:47 UTC, fedescarpa approved these changes

2021-04-08 19:08 UTC, merged